### ISSUE TITLE
Where is being "route" created?

### ISSUE THREAD

**Issue by ttodua** [AzuraCast/example-plugin#4]
I've followed the example provided in plugin to add `/my_custom_page` route.   For example, we want to add a menu page or whatever page, under Azuracast (to be accessible by admin, at `https://example.com/station/1/my_custom_page` and `https://example.com/admin/my_custom_page`

However, after restarting container `azuracast_web` , when i visit `mysite.com/my_custom_page`, I get:

> 404 Not Found
> The requested resource could not be found. Please verify the URI and try again.
> Go Back

 here the code in example-plugin:
```

$dispatcher->addListener(Event\BuildView::class, function(Event\BuildView $event) {
	$event->getView()->addFolder('my_custom_page', __DIR__.'/templates');
});

 
$dispatcher->addListener(Event\BuildRoutes::class, function(Event\BuildRoutes $event) {
	$app = $event->getApp();

	$app->get('/my_custom_page', \Plugin\ExamplePlugin\Controller\HelloWorld::class)->setName('example-plugin:sample:index')
	  ->add(\App\Middleware\EnableView::class);
	  
});

$dispatcher->addListener(App\Event\BuildAdminMenu::class, function (App\Event\BuildAdminMenu $e) {
	$router = $e->getRouter();
	$e->merge([
		'myCustomParentMenu' => [
			'label' => __('My example Menu'),
			'icon' => 'router',
			'items' => [
				'settings2' => [
					'label' => __('My example Menu Label'),
					'url' => $router->named('example-plugin:sample:index'),
					'permission' => Acl::GLOBAL_SETTINGS,
				]
			],
		]
	]);	

});

```

**Comment by ttodua** [comment]
I'll be also highly glad if provided an example to add route & menu under "station" page, because it has variable url (which includes station_id )... and I couldnt find how to hook into routes created by  `group`  declarations.

**Comment by ttodua** [comment]
@SlvrEagle23  @Vaalyn 
It's very pity, that there azuracast is left without any back, development or support. Not only it was not realistic to hire someone for azuracast development from your team, but neither you provide a generic q/a support for issues, which are not "custom" and not only related to 'specific person or needs'.

The issues I've created under this repo, is clearly not my personal issues, but would be useful for all users. However, you dont even answer the issues here. So, this means the development of this repo should be considered as half-abandoned (at least, I see so), with no way to get any answers or hints.

**Comment by ItsMitchh** [comment]
@ttodua 

I strongly am against your comments against the AzuraCast team who are working diligently through the past months to provide a solid experience for thousands of users of AzuraCast, your hostile attitude towards the AZ team is unacceptable and I suggest you find a different project that has the same level of love and care of AzuraCast and that is FOSS. But I'll be making some comments on your out of order remarks against Silver and Vaalyn.

You mention that they neither provide generic support, which is correct, AzuraCast is free and open source, there is no expectation of dedicated support that your requesting, this far exceeds general use from a typical user.  

The development of AzuraCast as a whole is not considered abandoned and far from it, it gets plenty of updates per week and thankfully the lovely people that provide back to Silver can put food on his table and keep a roof over his head, just because this repository doesn't get many updates doesn't mean anything, as it's clearly labeled as a `template`. 

You are always more than willing to contribute back to the AzuraCast repositories through a Pull request should you ever figure this out, cheers. 

Mitch.

**Comment by ttodua** [comment]
@SC2Mitch  Calm down mate, you have gone into attacking really. 
If you read someone's message and talking with me, then you make mistake. Please re-read my message , and stop slandering me about being hostile (if anyone is hostile here, it's you).
I've just expressed my thought that there was no support, and it was my worry (and what I said, was the fact).  No rudeness or hostility were posted here, other than your post.. 

Neither I said Azuracast was abanodned, as I said "this repository seems abandonded" (and i meant "this repository" which is "example-plugin" (and what i said, was a mere fact:  having 2- questions only and without getting even 1-line answer during 2 month).  So, accommodate the fact that use can open issues on github and post what they think.  And if you become angry on github when people open questions, then you don't have to read.
good luck.

**Comment by BusterNeece** [comment]
@ttodua Mitch has every right to be upset, and the rest of the team is also unhappy with how you've been speaking about our work.

Your specific words in the original post were:

> azuracast is left without any back, development or support.

You weren't referring to this particular repository but rather AzuraCast in its entirety.

This is entirely false; AzuraCast is very much not without any development work, and development is done every single day, despite the stresses of the real world and the pandemic bearing down on all of us.

We do provide a lot of support, and Vaalyn and Mitch are both instrumental in helping with that, while I focus mostly on technical bug reports that involve the application code itself. Together, we are able to provide a reasonably fast response time despite thousands of stations using our software.

In the open-source ecosystem, there is not much we can directly influence about who uses our work, but the one area we can control is who we offer personalized support to, and because of how you conduct yourself when interacting with us, we have chosen not to provide support to you.

**Comment by ttodua** [comment]
Well, I haven't thought you turn into such subjectiveness and even slight and correct critique (when someone hints to mistakes) would have lost your ability to objectively concern the topics. 
While you caught my phrase `azuracast is left without any back` , you have not read another phrase (which i have said 2 times, and not only one times what cought):

> The issues I've created under **this repo**, is clearly not my personal issues
and
> development of **this repo** should be considered as half-abandoned

moreover, I havent posted this issue under "AzuraCast" repository , and thus as I've opened topic under this repo ( and moreover I've mentioned "this repo" multiple times) everything was clear that i was referring to here, as my questions under "AzuraCast" main repo has been answered previously, and hadn't against that.

However, as it here seems inability to adequately understand the readings and clearly mentioning "A" is being read as "B" by you, and writing some thoughts (that very generic and useful-to-community, and not "personalized-to-me" questions have been unanswered almost 2 months)  were just mere facts, and I've just posted a question, asking if you could give "1-line answer" at least to give some hint to customer. 
even posting these two huge "responses" to my behavior, in that time, you could have answered all 3 open-issues on this repo, and everyone could have been happy.
However, you've read my sentences as if said "you inattentive bad guys" and you can't find any difference with my post.  i didn't thought you had such concerns to users and become such irritated with people's neutral thoughts. 
Ok, @SlvrEagle23  as you chosen not to answer my questions, I would stop posting anything with your azuracast repos. 
all the best.
